# Auto-labeling configuration for PRs

documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md', docs/**/*]

dependencies:
- changed-files:
  - any-glob-to-any-file:
    - pyproject.toml
    - uv.lock
    - .github/dependabot.yml

github-actions:
- changed-files:
  - any-glob-to-any-file: .github/workflows/**

configuration:
- changed-files:
  - any-glob-to-any-file:
    - pyproject.toml
    - '*.toml'
    - '*.yaml'
    - '*.yml'
    - .pre-commit-config.yaml

tests:
- changed-files:
  - any-glob-to-any-file: ['**/test_*.py', '**/*_test.py', tests/**/*]

pharia-sdk-core:
- changed-files:
  - any-glob-to-any-file: pharia_sdk/**/*.py

resources:
- changed-files:
  - any-glob-to-any-file: pharia_sdk/resources/**/*

examples:
- changed-files:
  - any-glob-to-any-file: examples/**/*
